### ISSUE TITLE
Nvy doesn't start

### ISSUE THREAD

**Issue by Hyvok** [RMichelsen/Nvy#10]
I tried compiling nvy and also installing it from a pre-compiled exe and in both cases the binary does absolutely nothing. There is nothing printed to a terminal and nothing appears on the screen.

**Comment by RMichelsen** [comment]
Hmm, could you post your Windows 10 version and your PC specs?

**Comment by Hyvok** [comment]
![win10](https://user-images.githubusercontent.com/1629028/95683389-8d450000-0bf3-11eb-92b1-7a8a681a1271.PNG)

PC with Ryzen 3600 and nVidia RTX 2070S.

**Comment by RMichelsen** [comment]
Hmm, I'm not sure. Can you try compiling it in debug mode? That way you may hit an assert with some more information.

**Comment by RMichelsen** [comment]
Oh and also, I assume you have `neovim` installed and available in your path? If so what version: `nvim -v`?

**Comment by Hyvok** [comment]
> Oh and also, I assume you have `neovim` installed and available in your path? If so what version: `nvim -v`?

Ah, nope! Maybe add a mention to the README so others won't make the same mistake. And maybe at least an error message if it is not found.

**Comment by RMichelsen** [comment]
> > Oh and also, I assume you have `neovim` installed and available in your path? If so what version: `nvim -v`?
> 
> Ah, nope! Maybe add a mention to the README so others won't make the same mistake. And maybe at least an error message if it is not found.

Yea, fair point. I'll add it to the README.
