### ISSUE TITLE
Some special characters break highlighting in statusline

### ISSUE THREAD

**Issue by EtiamNullam** [RMichelsen/Nvy#110]
Having some "special" characters (for example from a nerd font) in statusline will lead to invalid colors across statusline.

Running exactly the same command, with the same version of Neovim (0.9.5), but with two versions of Nvy (top: 0.3.7, bottom: 0.3.6), leads to two different results:

![image](https://github.com/RMichelsen/Nvy/assets/10875340/b4d2314f-c6cd-4502-bfd7-17acf66ab6cf)

The command should apply "function" highlight group to text "aaabbb":

```lua
:lua vim.o.statusline="%#function#aaabbb"
```

Seems like this bug was introduced in version 0.3.7 of Nvy, 0.3.6 is fine.

This problem is a bit broader for me as it affects both a bufferline plugin and a statusline plugin. This is my attempt to extract the problem so it can be reproduced without any plugins.

**Comment by Zorbn** [comment]
Thanks for providing the command that causes the issue! Does this still happen in 0.3.9? I was trying to reproduce it but I wasn't able to.

**Comment by RMichelsen** [comment]
I can't seem to reproduce this, if it still happens please reopen the issue.
