### ISSUE TITLE
C-w closes the window

### ISSUE THREAD

**Issue by pidgeon777** [RMichelsen/Nvy#111]
As the title say, `C-w` closes the Nvy window. I would like `C-w` (used for windows movements in `Neovim`, for example in conjunction with `h`, `j` etc.) not to close the window.

**Comment by Zorbn** [comment]
I wasn't able to get this to happen on 0.3.9 (the past versions I've used also didn't have this problem). Is it related to a Windows setting/other program/plugin/etc?

**Comment by VladimirMarkelov** [comment]
I use Nvy for a long time (now I use `0.3.9`) and `Ctrl+W` always worked as expected - I switched between splits with it. What does `:map` show?

**Comment by RMichelsen** [comment]
I can't reproduce this, please reopen with steps to reproduce in case it still occurs.
