### ISSUE TITLE
Weird character rendering related to line spacing

### ISSUE THREAD

**Issue by lopi-py** [RMichelsen/Nvy#112]
## Nvy:
![image](https://github.com/RMichelsen/Nvy/assets/70210066/3423f26b-8016-4208-a88d-18d69730150d)
Even with `--linespace-factor=1` it still happens, I need to set it to 0.8 but thats not great at all (it's too small).
## Alacritty:
![image](https://github.com/RMichelsen/Nvy/assets/70210066/9882837f-1455-4a0c-a679-fc2628074a03)
I think alacritty handles that because I set `font.offset` to 5, similar to `linespace-factor` option and it works great with no issues.
```toml
[font.offset]
x = 1
y = 5

[font.glyph_offset]
y = 3
```
------
No matters what font I use.

**Comment by Zorbn** [comment]
I think Alacritty has a custom way to draw those characters so that they will line up. Otherwise, they're just normal characters and will be separated by line spacing and things like that.

**Comment by RMichelsen** [comment]
You might be able to get rid of the spacing by using the `--linespace-factor=<float>` option, but other than that I don't think this is really something I want Nvy to support.
