### ISSUE TITLE
[Feature] Add `--neovim-bin` to select `nvim` binary path

### ISSUE THREAD

**Issue by pidgeon777** [RMichelsen/Nvy#116]
As the title says, it would be nice to add an argument to the `Nvy` executable so that it is possible to specify the `nvim` binary path (as implemented for example in `Neovide`).

**Comment by PavelDanov** [comment]
I've raised a PR for this. Feel free to try it out :)

**Comment by pidgeon777** [comment]
@underscoreHao Great! Are the Windows binaries available somewhere?

**Comment by PavelDanov** [comment]
PR hasn't been reviewed yet, but you can build the project yourself from my PR. I've also changed the README with example use. If you don't want want to build the project yourself shoot me an e-mail and I'll send you a binary including the change so you can test it out.

**Comment by RMichelsen** [comment]
Closed via #117
