### ISSUE TITLE
[Feature] Add option to hide mouse after certain amount of time.

### ISSUE THREAD

**Issue by mez0ru** [RMichelsen/Nvy#118]
I would like the ability to hide the mouse if it's inactive, as it sometimes obstructs my view of the code.
Since this is a GUI application, I believe it's possible to hide the mouse.

for example, add an option in neovim same as "guifont" for the timeout until mouse is hidden if inactive.

Thanks for this amazing application.

**Comment by PavelDanov** [comment]
I've added this functionality in a PR (will have to build the project yourself from my branch). You can try it out yourself and let me know how it goes :)

**Comment by RMichelsen** [comment]
Merged via #119! 👍
