### ISSUE TITLE
WSL support

### ISSUE THREAD

**Issue by FlyinCow** [RMichelsen/Nvy#122]
It would be nice to have WSL support like neovide, maybe an option like `nvy --wsl`. It seems that neovide is doing this by call `wsl nvim`.

**Comment by RMichelsen** [comment]
Unfortunately I think due to the way Nvy pipes input and output it is not as simple as running `wsl nvim` instead of `nvim`, I am open to a workaround but I don't think we should change the fundamentals of how Nvy communicates with nvim.
