### ISSUE TITLE
Nvy does not open file with space in path properly

### ISSUE THREAD

**Issue by R00dRallec** [RMichelsen/Nvy#129]
When opening a file with a space in the path (e.g. in the folder name), the file is not opened properly.
Instead two 'new' files are opened, see screenshots below.

The issue occurs with Nvy 0.4.0.
The issue occurs with Nvy 0.4.0 without config (-u NONE)
The issue **does not occur** with Nvy 0.3.9.
The issue **does not occur** when using nvim (0.10.1) directly from the console.

**Console**
![image](https://github.com/user-attachments/assets/397c0cab-fd06-4e85-b11d-9898420da7f1)
`nvim "C:\Users\user\test folder\test.txt"`

**Nvy 0.3.9**
![image](https://github.com/user-attachments/assets/f74f1a16-0542-42f8-8f9a-d5a3f9ac28fc)
`Nvy_039.exe "C:\Users\user\test folder\test.txt"`

**Nvy 0.4.0**
![image](https://github.com/user-attachments/assets/f465ca46-bef5-4c9d-8581-7f5ac3a3410c)
![image](https://github.com/user-attachments/assets/94f27302-dbb6-4206-83f5-ab24a409aff4)

`Nvy.exe "C:\Users\user\test folder\test.txt"`

**Nvy 0.4.0 -u NONE**
![image](https://github.com/user-attachments/assets/62e80581-59ea-4f24-a7f1-520ac773af57)
`Nvy.exe -u NONE "C:\Users\user\test folder\test.txt"`

**Comment by R00dRallec** [comment]
Issue reproducible with Nvy Release 0.4.0.
Cannot reproduce when building [cfcea51](https://github.com/RMichelsen/Nvy/commit/cfcea518a2e4b19f0b97b6074cc5cd0f27275101) locally.

**Comment by RMichelsen** [comment]
Fixed by #131 in Nvy 0.4.1

**Comment by ueffel** [comment]
It's still not fixed with the asset <https://github.com/RMichelsen/Nvy/releases/download/v0.4.1/Nvy.exe> in the v0.4.1 release.
This asset has `ProductVersion: 0.4.0.2-g3e04fc8` if the `3e04fc8` is the commit hash, it is one commit behind the commit tagged with v0.4.1
Can you please check if you provided the correct asset in the release?

**Comment by RMichelsen** [comment]
You're right, I messed up the compilation. It should work now!

**Comment by ueffel** [comment]
It does work now. Thanks.
