### ISSUE TITLE
Text decorations not working with certain fonts

### ISSUE THREAD

**Issue by cpkio** [RMichelsen/Nvy#13]
Cascadia Code [PL] font seems to be not working in Nvy — enabling spell check shows no text decorations. Same font works in NeovimQT. Worth noting Iosevka and JuliaMono are working as expected.

## Neovim QT
![2020-11-09_134231](https://user-images.githubusercontent.com/1917113/98531667-b8be1780-2291-11eb-9770-92b50e7b12c6.png)

## NVy
![2020-11-09_134340](https://user-images.githubusercontent.com/1917113/98531682-beb3f880-2291-11eb-943e-c67aa9c02c22.png)

**Comment by RMichelsen** [comment]
I'll look into this, at the moment DirectWrite determines the width of the underline, perhaps for this font it is too small or not defined or something. Might need to put a minimum value on it then.

**Comment by cpkio** [comment]
I'm using Cascasia [latest](https://github.com/microsoft/cascadia-code/releases/tag/v2009.22).

**Comment by RMichelsen** [comment]
With a default config `:setlocal spell` gives me underlines for misspelled words with `Cascadia Code` and `Cascadia Code PL`:
![image](https://user-images.githubusercontent.com/42123601/98535677-cb7f1f00-2286-11eb-86e6-b53fb89477eb.png)
Can you check if this happens for you with an empty `init.vim`? (apart from setting the font)

**Comment by cpkio** [comment]
Started Nvy with `-u NONE`, with all the plugins removed. Still the same: no underlines with Cascadia Mono, and underlines with Iosevka.

**Comment by RMichelsen** [comment]
Can you try to run this version of `Nvy` and see if it prints out anything when underlines are supposed to appear? It should print out the thickness of the underline.
[Nvy.zip](https://github.com/RMichelsen/Nvy/files/5510292/Nvy.zip)

**Comment by RMichelsen** [comment]
[Nvy.zip](https://github.com/RMichelsen/Nvy/files/5510381/Nvy.zip)
Please see if this version works for you.

**Comment by cpkio** [comment]
Working for me, thanks.
