### ISSUE TITLE
Support patched fonts

### ISSUE THREAD

**Issue by sprainbrains** [RMichelsen/Nvy#14]
OS Windows 10
Nvy 0.1.7

![image](https://user-images.githubusercontent.com/10284309/98857844-afd76c80-2470-11eb-8824-4d20d24d5118.png)
The current version is not display patched fonts (in my case it is JetBrains Mono)

![image](https://user-images.githubusercontent.com/10284309/98858030-fcbb4300-2470-11eb-8526-f368842672d9.png)
In Neovim-qt

**Comment by RMichelsen** [comment]
Could you send me a link to the patched font and I'll try to figure out why this isn't working. In theory I see no reason why `Nvy` should not be able to handle this.

**Comment by sprainbrains** [comment]
> Could you send me a link to the patched font and I'll try to figure out why this isn't working. In theory I see no reason why `Nvy` should not be able to handle this.

Ok. No problem. Link [here ](https://github.com/ryanoasis/nerd-fonts#font-installation)

**Comment by sprainbrains** [comment]
Oh sorry. I found solution) 
I wrote incorrect font name in init.vim

**Comment by RMichelsen** [comment]
No worries, good to hear it works.
