### ISSUE TITLE
Properly handle file paths with spaces

### ISSUE THREAD

**Issue by ika-musuko** [RMichelsen/Nvy#15]
OS: Windows 10 x64
Nvy 0.1.7

Nvy does not properly handle filepaths with spaces. 

Steps to reproduce:
1. Create a file with spaces
2. Open it with Nvy

Expected behavior:
- The file opens and can be edited

Actual behavior:
- The filepath is split by space and each token opens in their own buffers

Screenshot:
![image](https://user-images.githubusercontent.com/32429059/99626121-604fee00-29e6-11eb-8f15-6ce80045ef79.png)

**Comment by ika-musuko** [comment]
By the way, it seems that even if I try to run Nvy from the command line like `Nvy "nice man.txt"`, this problem still occurs.

**Comment by RMichelsen** [comment]
This issue is fixed in [Nvy 0.1.8](https://github.com/RMichelsen/Nvy/releases/tag/v0.1.8)

**Comment by ika-musuko** [comment]
Thanks for the quick fix!
