### ISSUE TITLE
Open a file by dragging it onto Nvy

### ISSUE THREAD

**Issue by ika-musuko** [RMichelsen/Nvy#16]
This is a feature request. It would be nice to be able to drag a file from say, the File Explorer onto an open instance of Nvy and have the file open.

**Comment by RMichelsen** [comment]
You should now be able to drag files onto Nvy, in the newest release [Nvy 0.1.8](https://github.com/RMichelsen/Nvy/releases/tag/v0.1.8)

**Comment by ika-musuko** [comment]
Thank you, it works!

Would it be possible to implement dragging multiple files at once, and having Nvy open all of them?

**Comment by RMichelsen** [comment]
Done, try [Nvy 0.1.9](https://github.com/RMichelsen/Nvy/releases/tag/v0.1.9). I didn't test it thoroughly, but it should work.

**Comment by ika-musuko** [comment]
Hmm, I tried it but it doesn't seem to work
![nvymultidrag](https://user-images.githubusercontent.com/32429059/99857715-b89b0300-2b40-11eb-8e5d-14a3913d23c3.gif)

**Comment by RMichelsen** [comment]
They should be opened if you type `:buffers`, essentially it is just running `:e <filename>` for each file. Did you intend for something else to happen? (or is it not opening them as buffers at all?)

**Comment by ika-musuko** [comment]
I am using a plugin that shows all of the loaded buffers as "tabs" at the top, but here's a screenshot of :buffers after a multi-select drag event.
![image](https://user-images.githubusercontent.com/32429059/99858043-7f16c780-2b41-11eb-834d-9ef737431716.png)

For reference, here's a screenshot of what I expected the behavior to be after a multi-select drag event (I manually opened all of these files one at a time for the purposes of this screenshot)
![image](https://user-images.githubusercontent.com/32429059/99858148-beddaf00-2b41-11eb-909b-0fbae813d414.png)

**Comment by RMichelsen** [comment]
Hmm, I can't seem to reproduce it.
![nvy_test](https://user-images.githubusercontent.com/42123601/99858463-e8bcc300-2b8d-11eb-8750-636ec1050379.gif)

Can you try with an empty config, although it confuses me why that would be an issue.

**Comment by ika-musuko** [comment]
Ah I noticed after downloading the 0.1.9 executable, its timestamp was different and now it works. Either I accidentally re-downloaded the 0.1.8 executable originally, didn't click "Yes" to overwrite file, or the 0.1.9 executable was updated during the course of this thread.

In any case, thank you for your prompt work on my tickets and for creating such a fast and minimalist Neovim client for Windows. Do you have anything setup for donations?

**Comment by RMichelsen** [comment]
No worries, happy it works.

I don't have anything set up for donations, never really thought about it, maybe in the future :)
