### ISSUE TITLE
Add option to modify line spacing and character spacing.

### ISSUE THREAD

**Issue by bytesiz3d** [RMichelsen/Nvy#17]
This is a **feature request**. I personally like to use Fira Code on Windows 10 x64. And I'm really enjoying using Nvy as my daily driver now, but the character height in Fira Code (in general) is not very high. I was hoping Nvy would have the option to add custom line spacing and character spacing, for improved clarity.

**Comment by RMichelsen** [comment]
You can now modify the line spacing with `--linespace-factor=<FLOAT>` e.g. `--linespace-factor=1.2` to multiply the line spacing by `1.2`. Modifying the character spacing is a bit more tricky and I would rather not support that at this moment. Link to new release: [Nvy 0.1.8](https://github.com/RMichelsen/Nvy/releases/tag/v0.1.8)
