### ISSUE TITLE
Feature: help command

### ISSUE THREAD

**Issue by VladimirMarkelov** [RMichelsen/Nvy#19]
I see that `nvy` is getting more and more options. It is great. Unfortunately, there is no way to learn what options are available(e.g, I doubt anyone can guess new one `--disable-ligatures` :) ). I propose adding `--help`/`-h` flag to display what options exist. 

This `--help` output should also include the binary version - I do not know how to check current version because `nvy --version` does nothing.

**Comment by RMichelsen** [comment]
Thats a good idea, I'll implement this for the next version.
