### ISSUE TITLE
[Feature Request] add a cli option to pass nvim path

### ISSUE THREAD

**Issue by hosxy** [RMichelsen/Nvy#20]
Could you please add a cli option like `--nvim-path` to pass path of nvim.exe?
Because sometimes Nvy.exe and nvim.exe are not in same directory.

**Comment by RMichelsen** [comment]
Hmmm, I'm not sure this makes sense, usually you would add `nvim.exe` you your `PATH` environment variable and it will find it without them being in the same directory.

**Comment by hosxy** [comment]
There are some other exe file in `neovim\bin`(like `curl.exe`, and Windows also have `curl.exe` itself), I don't want to add them to `PATH` to avoid some strange problem.

**Comment by RMichelsen** [comment]
Presumably `neovim` packages `curl.exe` in case it is not already bundled with your Windows installation, in that case can't you just delete `curl.exe` from the `neovim\bin` folder, and add it to your path?

**Comment by hosxy** [comment]
Thanks for you help, I find a pretty good way, only modify `start in` in shortcut(.lnk) like this
![图片](https://user-images.githubusercontent.com/17108640/99951823-a7106000-2db9-11eb-86c7-ad8a0cd68a39.png)
now it work well

**Comment by RMichelsen** [comment]
Good to see you found a solution 👍
