### ISSUE TITLE
Feature: Read text from stdin

### ISSUE THREAD

**Issue by bytesiz3d** [RMichelsen/Nvy#21]
nvim has the ability to read text from stdin by adding a single (-) as a command line argument. I was hoping this feature would also be available in Nvy as it would make my life so much easier.

**Comment by RMichelsen** [comment]
Hmmm, I'm not sure. I can have `Nvy` forward all arguments after and including `-` to `nvim`, but I don't think this solves your issue. Presumably I'd need to read from stdin and redirect it to `nvim` through the `nvim` API, I think this might be a bit of a bigger thing to implement, which I'm not too happy about. If you have any ideas on how this could be done in a simple way, I'll take a look.

**Comment by RMichelsen** [comment]
I will close this issue for now, if there is more interest in pursuing this please reopen and I'll reconsider, maybe with a proposal for a solution as well.
