### ISSUE TITLE
IME window does not appear below the cursor, and the current input buffer text does not show up

### ISSUE THREAD

**Issue by ika-musuko** [RMichelsen/Nvy#23]
You'll need to have Chinese, Japanese, Korean or any sort of language requiring an input method installed.

When using one of the above languages, the suggestions window does not appear below the cursor and the currently inputted text also does not appear. See the images below for examples.

Expected (from another application)
![image](https://user-images.githubusercontent.com/32429059/101419830-b4dbe000-38a5-11eb-844f-cc8526f137f5.png)

Actual (from Nvy)
![image](https://user-images.githubusercontent.com/32429059/101419871-ccb36400-38a5-11eb-9e59-cd2188063aeb.png)

**Comment by RMichelsen** [comment]
Hmm, I don't have a good idea of why this is happening, I'll try to investigate. I don't have much time at the moment, so it might take a while before this is fixed. Feel free to open a PR if you find a solution.
