### ISSUE TITLE
Flash on window resize

### ISSUE THREAD

**Issue by guardam** [RMichelsen/Nvy#24]
I noticed that the window flashes when resizing it.

**Comment by RMichelsen** [comment]
I agree this is not ideal, I'm not sure if there is an easy way to fix this if contents are still to be shown while resizing. In case a solution is non-trivial, would you prefer a black window during resize or the current behaviour?

**Comment by guardam** [comment]
I see that neovide for example stops the rendering while the window is resizing, and after that it redraws given the new window constraints. I think this is at least better than having the window flash, but yeah the long term hard solution would be to have the content adapt while resizing.
