### ISSUE TITLE
Drag and drop doesn't work correctly with splits

### ISSUE THREAD

**Issue by guardam** [RMichelsen/Nvy#25]
If I have for example a vertical split between two windows and I try to drag a file in the right split, it gets opened in the left one.

**Comment by RMichelsen** [comment]
This is the expected behaviour atm, since drag and drop just calls `:e <FILE>`. Do you see an easy way to fix this? We might be able to register a mouse-click with `nvim` for the mouse cursor position at the time of the drag, this might work? Feel free to open a PR if you find a fix.
