### ISSUE TITLE
Smooth scrolling

### ISSUE THREAD

**Issue by guardam** [RMichelsen/Nvy#26]
This is not necessary, but it would be really cool.  
<https://github.com/Kethku/neovide/issues/62>  
<https://github.com/neovim/neovim/pull/11748>

**Comment by RMichelsen** [comment]
I might look into this in the future, I personally don't like smooth scrolling, but I can see that a lot of people do, so it may be worth looking into.

**Comment by RMichelsen** [comment]
I will close this issue for now, if there is more interest in pursuing this please reopen and I'll reconsider, maybe with a proposal for a solution as well.

**Comment by yashamon** [comment]
Seconded, please reopen. After using neovide, no smooth scroll is very jarring, and uncomfortable. Smooth cursor is also amazing. 
It would be good to give neovide some competition.

**Comment by pidgeon777** [comment]
Also interested in smooth scrolling. Maybe it could be toggled with a command line argument?
