### ISSUE TITLE
WSL Neovim

### ISSUE THREAD

**Issue by guardam** [RMichelsen/Nvy#27]
It would be cool if Nvy could also use Neovim running on WSL as the backend.

**Comment by RMichelsen** [comment]
I am unsure how feasible this is given that `Nvy` runs nvim with `nvim --embed` which expects certain well-defined behaviour from the GUI. For `Nvy` to work with WSL we would need some way of running `nvim` as a server.

**Comment by guardam** [comment]
It seems that neovide just uses `wsl nvim` instead of `nvim`

https://github.com/Kethku/neovide/blob/94187f1180326324d98a2791214832337b8110d4/src/bridge/mod.rs#L44-L50
