### ISSUE TITLE
Nvy 0.21 crash on start

### ISSUE THREAD

**Issue by cpkio** [RMichelsen/Nvy#31]
![2021-01-19_084351](https://user-images.githubusercontent.com/1917113/104992671-946d7c80-5a32-11eb-970d-5ff45b479da9.gif)
0.20 is working fine.

**Comment by RMichelsen** [comment]
My apologies, the [release](https://github.com/RMichelsen/Nvy/releases/tag/v0.2.1) should be fixed now
