### ISSUE TITLE
request only instance

### ISSUE THREAD

**Issue by lilixiong2018** [RMichelsen/Nvy#32]
I thank it will be great if it can be  only one instance, then anytime I run "nvy anotherfile", it active previous Nvy instance (if  had) and then open  anotherfile to edit.

**Comment by RMichelsen** [comment]
This is a good idea, by doing this though we would restrict Nvy to a single instance at all times which I think is not ideal default behaviour for all users. Maybe it should be implemented as a flag `--single-instance`, what do you think?

**Comment by EtiamNullam** [comment]
I think having only one instance is far from ideal. I'm okay with opening many `Nvy` windows as they are light and open quickly but I understand how some people would want to reduce potential clutter and wasted resources, especially if someone has bloated `nvim` with many heavy plugins (I recommend cleaning it instead if possible).

Maybe something like "sessions" would work. For example: when first time `Nvy` is open with `--session=work` a new window is open, but the next time this option is passed it will just open that file in that instance and bring focus to it. This way we can benefit both from multiple instances and reduced clutter.

I'm just afraid this feature will introduce unnecessary complexity and make `Nvy` harder to maintain. Some simple solution is needed if at all.

**Comment by RMichelsen** [comment]
I will close this issue for now, if there is more interest in pursuing this please reopen and I'll reconsider, maybe with a proposal for a solution as well.
