### ISSUE TITLE
Drag and drop does not work with cyrillic characters in path or filename

### ISSUE THREAD

**Issue by latkinsv** [RMichelsen/Nvy#34]
In case if path or filename include cyrillic characters Nvy can't open it by drag and drop.  It just creates an empty buffer:
![nvy_ddfail](https://user-images.githubusercontent.com/54598211/124719353-b8087e80-df0f-11eb-8bbc-bd59f23117b8.PNG)

The same file opened by double clicking:
![nvy_cyrfname](https://user-images.githubusercontent.com/54598211/124719541-ee45fe00-df0f-11eb-9328-3e904d8ce0ae.PNG)

This has been tested on Windows 10.

**Comment by RMichelsen** [comment]
Fixed and merged in #35, new release at: https://github.com/RMichelsen/Nvy/releases/tag/v0.2.2
