### ISSUE TITLE
FocusLost event missing

### ISSUE THREAD

**Issue by Perry3D** [RMichelsen/Nvy#37]
Hi,

i currently have this autocommand in my configuration:

```autocmd FocusGained,FocusLost * rshada|wshada```

The shada file gets written when i used nvim-qt but not when i use nvy.

Is this something nvy doesn't want to implemt or a bug?

**Comment by RMichelsen** [comment]
Thanks for the report,

Please see if this new release works for you. I've tested it very briefly and it looks to work on my end:
https://github.com/RMichelsen/Nvy/releases/tag/v0.2.3

**Comment by Perry3D** [comment]
Thank you for the very fast support. Tested it and both events work fine.
