### ISSUE TITLE
Version 0.2.4 does not start

### ISSUE THREAD

**Issue by VladimirMarkelov** [RMichelsen/Nvy#39]
Windows 10 64 bit, I installed the latest 0.2.4, opened a file to edit with `nvy.exe --geometry=190x42 ttdl.json` and got this: 

```
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Assertion failed!

Program: D:\neovim\bin\Nvy024-.exe
File: C:\Users\Rasmus\Documents\Nvy\src\renderer\renderer.cpp
Line: 32

Expression: ret == S_OK

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enabled)
---------------------------
Abort   Retry   Ignore   
---------------------------
```

Rolled back to 0.2.3 which works fine.

**Comment by RMichelsen** [comment]
Hmm, I can't seem to reproduce this on my end. The error you're getting seems to suggest it cannot create the D3D11 device which is odd. It shouldn't even hit any code path introduced in 0.2.4. Would it be possible for you to try and compile from source and see if the problem persists then?

**Comment by VladimirMarkelov** [comment]
Here is the error I see:

```
warning: D3D11CreateDevice: Flags (0x
warning: 2
warning: ) were specified which require the D3D11 SDK Layers for Windows 10, but they are not present on the system.
These flags must be removed, or the Windows 10 SDK must be installed.
warning: Flags include:
warning: D3D11_CREATE_DEVICE_DEBUG
warning:
warning: Assertion failed!
```

Does it fail because `nvy.exe` is debug build? Size of 0.2.4 is twice more than the previous version.

**Comment by RMichelsen** [comment]
Oh! I must have compiled in debug by mistake, I will fix and reupload later today.

**Comment by RMichelsen** [comment]
> Size of 0.2.4 is twice more than the previous version.

I was quite surprised that the imm.lib would add 100KB, makes more sense now that I realize it was a debug build :facepalm:

The [release](https://github.com/RMichelsen/Nvy/releases/tag/v0.2.4) has now been updated, hopefully this fixes the issue.

**Comment by VladimirMarkelov** [comment]
Thanks! The update binary works great,
