### ISSUE TITLE
Nerd/Patched font support

### ISSUE THREAD

**Issue by vignesh0025** [RMichelsen/Nvy#4]
I am not able to select the font for the interface using "set guifont=" ( In my case, I am using "FiraCode NF"). Going through the source, I found Consolas font hardcoded in the RendererInitialize function. I changed the font and get it working perfectly. 

Is there going to be any update on the same ? or shall I work with reading the variable from the vimrc and update the font in the renderer and ( give a pull request if I could get it working ) ?

**Comment by RMichelsen** [comment]
Consolas is hardcoded as the fallback font, setting the guifont should still work. Did you ensure to do `set guifont=FiraCode\ NF` (to escape the space)? Either way I'll be working on a fix to the guifont issues today, there are some problems with the way initialization of the UI is done atm.

**Comment by vignesh0025** [comment]
I did escape the space and no, it did not update the UI
![image](https://user-images.githubusercontent.com/60247919/94337962-0ba67d00-000c-11eb-8cd8-8f72f4bff556.png)

Whereas, hardcoding FiraCode NF (as fallback) did work as expected. 

Off topic: Its been very long since I worked with Direct X and so, I am revising all the basics to contribute. Is there any resource particular to Direct 2D and stuffs ?

**Comment by RMichelsen** [comment]
I'm not sure why that is not working for you, if you download the first release `v0.1` does this behaviour also exist there? I removed the last release since the initialization is broken, I'm working on a fix atm but its not as trivial as I'd like.

For the DirectX stuff, MSDN is your best friend for [DirectWrite](https://docs.microsoft.com/en-us/windows/win32/directwrite/direct-write-portal) (and D2D, D3D...), also I can recommend joining the DirectX discord server, there are usually experienced people there if you run into problems.

**Comment by vignesh0025** [comment]
> I'm not sure why that is not working for you, if you download the first release `v0.1` does this behaviour also exist there? I removed the last release since the initialization is broken, I'm working on a fix atm but its not as trivial as I'd like.

Its the same with v0.1. UI's not updating with the new font. 

> For the DirectX stuff, MSDN is your best friend for [DirectWrite](https://docs.microsoft.com/en-us/windows/win32/directwrite/direct-write-portal) (and D2D, D3D...), also I can recommend joining the DirectX discord server, there are usually experienced people there if you run into problems.

Thanks! I will look into it.

**Comment by RMichelsen** [comment]
> Its the same with v0.1. UI's not updating with the new font.

Ill look into this as soon as I fix the initialization issues. Shouldn't be long, I think I'm just opting to read from the `init.vim` and parsing it myself to find the guifont setting.

**Comment by RMichelsen** [comment]
I think this commit should fix the initialization problems. On my end I can change the guifont while the UI is running, if you do `set guifont=Consolas:h10` then `set guifont=Consolas:h20` does this not work for you either? 

I'll upload a new release for you to download in case you want to avoid compiling yourself

**Comment by vignesh0025** [comment]
I pulled the changes and recompiled it. Changing fonts works only if we mention the font size with the family.

```
set guifont=Consolas:h10             " works
set guifont=Consolas:h20             " works
set guifont=FiraCode\ NF:h10         " works

set guifont=FiraCode\ NF            " Doesn't work
set guifont=Consolas                " Doesn't work

```

Thanks for the effort. I actually went deep into DirectX API MSDN.

**Comment by RMichelsen** [comment]
Alright, I'll consider the issue fixed then, I added a note on the README to let people know that you have to specify the font size for it to work :)

**Comment by cpkio** [comment]
Can you test Nvy-latest with _Iosevka Term_ font [family](https://github.com/be5invis/Iosevka/releases)?

It seems to me _Nvy_ cannot catch up with a font with more than one space: `set guifont=Iosevka\ Term\ Heavy\ Extended:h12` works in _Neovim_ but not in _Nvy_.

**Comment by RMichelsen** [comment]
> Can you test Nvy-latest with _Iosevka Term_ font [family](https://github.com/be5invis/Iosevka/releases)?
> 
> It seems to me _Nvy_ cannot catch up with a font with more than one space: `set guifont=Iosevka\ Term\ Heavy\ Extended:h12` works in _Neovim_ but not in _Nvy_.

This is because `Nvy` doesn't support setting the weight in the name, `Iosevka\ Term:h12` will work for you, but now you won't be getting the `Heavy Extended` as a default. I'll investigate this to see if its possible to somehow make DirectWrite recognize the font weights.
