### ISSUE TITLE
Visual glitches during resizing and persisting afterwards until window is moved

### ISSUE THREAD

**Issue by EtiamNullam** [RMichelsen/Nvy#48]
While resizing window by grabbing a border windows there are visual glitches, flashing and jumping content.

After we stop resizing we end up with a glitched window. Glitched window is still interactive and will stay like this until window is moved.

https://user-images.githubusercontent.com/10875340/165650462-b5019b65-029e-44a1-a158-c0bdfd1025ad.mp4

~~I think its a regress as #30 is saying its fixed.~~ - Never mind its a different problem.

**Comment by RMichelsen** [comment]
I apologize for the very slow response. I can't seem to reproduce the flickering/resizing glitchy behaviour. What platform are you on? And does it happen with an empty neovim configuration?

**Comment by EtiamNullam** [comment]
No problem. I'm glad you're back :)

I'm sorry, I didn't notice when it got fixed. Apparently while dragging the border box of `Nvy` it's no longer updated continuously and only updates once on release. Same on previous `Nvy` releases. Maybe it was changed in `Neovim` itself?

Can't reproduce the problem anymore, so I'm closing it.

Thank you for bringing such snappy and light `Neovim` client/GUI!
