### ISSUE TITLE
Windows keyboard input

### ISSUE THREAD

**Issue by cpkio** [RMichelsen/Nvy#5]
Nvy cannot input unicode characters with CTRL-ALT-<key>, which is a normal windows input method. I've found out `<F13>`-`<F24>` aren't available either.

**Comment by RMichelsen** [comment]
Hmm, I'm unsure what you mean, CTRL-ALT- works on my end if I bind something like `<C-M-(any key)>` and it is distinguished from binds like `<C-(any key)>`. Also not sure how it relates to unicode characters. You can input those by going insert mode and pressing `Ctrl+V` then some code `UAC00`. Can you be a bit more specific about what doesn't work and I'll try to fix

**Comment by cpkio** [comment]
Windows uses keyboard layouts, which can be customized and made from scratch. A standard tool for this is Microsoft Keyboard Layout Creator 1.4, which I cannot find on the Microsoft site now, but is is widely available elsewhere. This tool allows you to edit or create new keyboard layouts, and create a setup package.

This layouts use windows mechanisms, allowing you to input predefined symbols from unicode range by pressing a combination of keys or a sequence of keys. For example, my layout allows me to input `«` and `»` by pressing `AltGr+<` and `AltGr+>` (AltGr is treated as CTRL+ALT). `AltGr+a` gives me `≈`, and `AltGr+x` gives `×`, which are obviously inconvinient to input by copypasting or anything. Dead keys allow pressing a key like `AltGr+:` _then_ `o` and get `ö` as a result.

A standard Windows-shipped belgian AZERTY layout has a `^` dead key, which allows french-speaking users to input `â`, `ê`, `û` by pressing `a`, `e`, `u` after that dead key.

**Comment by RMichelsen** [comment]
I've added F13-F24 in the latest commit, I need to figure out how to fix the deadkey/unicode input issue still.

**Comment by cpkio** [comment]
Maybe looking into QT sources will help: both nvimQt and goneovim I've been using before are using QT and work as expected.

**Comment by RMichelsen** [comment]
Could you please try again with the newest commit and see if the issue is resolved? If you need me to build it I can put up a new release.

**Comment by cpkio** [comment]
Yes, build it please. I've tried building it yesterday, but as I dont have VS I tried to use cmake -> gcc + make files, and it turns out I dont have required headers.

**Comment by RMichelsen** [comment]
> Yes, build it please. I've tried building it yesterday, but as I dont have VS I tried to use cmake -> gcc + make files, and it turns out I dont have required headers.

Here you go, [Nvy 0.1.3](https://github.com/RMichelsen/Nvy/releases/tag/v0.1.3)

**Comment by VladimirMarkelov** [comment]
Downloaded 0.1.3 from releases: combinations <Ctrl+w> + h/j/k/l do not work (at least I failed to move to the right split with `Ctrl+w l`

**Comment by cpkio** [comment]
These are my CTRL+ALT+? and CTRL+SHIFT+ALT+? layouts. Greens are working, others are not.
![CTRL-ALT](https://user-images.githubusercontent.com/1917113/94527336-7ab7e780-023f-11eb-9b95-d05e9a03f71e.png)
![CTRL-SHIFT-ALT](https://user-images.githubusercontent.com/1917113/94527341-7be91480-023f-11eb-9ac5-ce54c0518bcb.png)
The THSP above is Thin Space U+2009.

It seems ALT-D and ALT-W aren't working too.

**Comment by RMichelsen** [comment]
> Downloaded 0.1.3 from releases: combinations <Ctrl+w> + h/j/k/l do not work (at least I failed to move to the right split with Ctrl+w l

> It seems ALT-D and ALT-W aren't working too.

These ones are odd, I think I broke something then, I'll look into it shortly.


> These are my CTRL+ALT+? and CTRL+SHIFT+ALT+? layouts. Greens are working, others are not.

This is more tricky as I don't have an equivalent layout to test with, so some of the altgr and deadkey combinations work for you now? I tested on my Danish layout, will try to test more extensively later.

**Comment by cpkio** [comment]
It seems like only the symbols from lower range are input normally. ¹, ² and ³ are U+00B9, U+00B2 and U+00B3, « and » are U+00AB and U+00BB. Not working ⁴, ⁵ and ⁶ for example are U+2074, U+2075, U+2076.

**Comment by RMichelsen** [comment]
> It seems like only the symbols from lower range are input normally. ¹, ² and ³ are U+00B9, U+00B2 and U+00B3, « and » are U+00AB and U+00BB. Not working ⁴, ⁵ and ⁶ for example are U+2074, U+2075, U+2076.

That seems plausible, I might have made an assumption about the length of the ASCII encoded string that breaks this. I'll investigate when I get home in a few hours.

**Comment by RMichelsen** [comment]
Alright, after some hours of research I really hope this works. Had a look at the source code of gvim to see how they solve some of the issues with dead chars. The win32 input model is kinda wonky with separate processing for `WM_KEYDOWN` and `WM_CHAR`. I'll update the 0.1.3 release so its not broken anymore, let me know if it works for you please.

**Comment by VladimirMarkelov** [comment]
At least `Ctrl+w <movement>` works fine again :) Thanks!

**Comment by cpkio** [comment]
Thank you, it _almost_ works. U+00A0 (no-break space) and U+202F (narrow no-break space) aren't working, U+0020 (space) is inserted instead. Probably anything involving pressing space + modifiers is affected.

**Comment by RMichelsen** [comment]
> Thank you, it _almost_ works. U+00A0 (no-break space) and U+202F (narrow no-break space) aren't working, U+0020 (space) is inserted instead. Probably anything involving pressing space + modifiers is affected.

**Comment by RMichelsen** [comment]
> Thank you, it _almost_ works. U+00A0 (no-break space) and U+202F (narrow no-break space) aren't working, U+0020 (space) is inserted instead. Probably anything involving pressing space + modifiers is affected.

Hmm.. frustrating edge cases. I'll need to download that keyboard layout thing and test vs gvim or neovim-qt I think. Do you know if it works on those? Also can you hop on https://gitter.im/neovim/neovim and message me there, maybe you can help me debug this one, since I can't easily test it with my layout.

**Comment by cpkio** [comment]
I've been using this layout for years now. It does work in Vim, gVim, Neovim, NeovimQT and goNeoVim.

If you would like to test this, I've made an [archive](https://workupload.com/file/fKdLvH6Urpv) for you. It contains `usatypo` directory with a layout installation package (standard windows installer, can be uninstalled as usual from Control Panel, if layout not set as default), `MSKLC.exe` which is a installation package of Microsoft Keyboard Layout Creator, and a `USATypo.klc` file, which is a text file describing the layout.

This `.klc` file can be compiled to installation package by MSKLC if no layout with same internal name (`USATypo` for this) is installed in the system.

So, you can install the layout and test in in any editor, or install the MSKLC, load the layout and test it there (**Project** -> **Test keyboard layout…** menu item).

**Comment by RMichelsen** [comment]
So I think I've fixed the issue, atleast NBSP and Narrow NBSP cause my lines to break early (put both words on a new line). However I also found this behaviour to be true in the v0.1.3 release, please try the new one and tell me if it works.

**Comment by cpkio** [comment]
Made a small video for you with 0.14 version. Some keys work, but most stopped working. Nirsoft tool shows pressed keys with some delay.
![2020-10-01_10-39-03](https://user-images.githubusercontent.com/1917113/94781401-6f48f580-03d2-11eb-8a26-20297f22e092.gif)

**Comment by RMichelsen** [comment]
I've reverted back the change (Changed the [v0.1.4](https://github.com/RMichelsen/Nvy/releases/tag/0.1.4) release), on my end NBSP/Narrow NBSP seem to work, can you confirm that they still aren't working?

**Comment by cpkio** [comment]
I don't understand how you input NBSP and THIN SPACE symbols. On my end pressing CTRL-ALT-SPACE and CTRL-SHIFT-ALT-SPACE input regular 0x20 spaces. On the gifs below `*` is NBSP char, and `~`/`·` is regular space.

![2020-10-01_15-11-30](https://user-images.githubusercontent.com/1917113/94807936-ff9a3100-03f8-11eb-9f32-f2b591f0fa26.gif)
![2020-10-01_15-12-47](https://user-images.githubusercontent.com/1917113/94807942-01fc8b00-03f9-11eb-91bf-1558cf4140da.gif)

**Comment by RMichelsen** [comment]
Okay, try once again (Changed the [v0.1.4](https://github.com/RMichelsen/Nvy/releases/tag/v0.1.4) release), I now process SPACE as every other character, this should mean that your nbsp keybinds should work with space as the modifier. I was testing the NBSP output in general which worked, but VK_SPACE was handled separately.

**Comment by cpkio** [comment]
Works as expected. Closing.
