### ISSUE TITLE
Is it possible to make underline thicker?

### ISSUE THREAD

**Issue by dkchshv** [RMichelsen/Nvy#54]
Is it possible to make underline thicker? Like in nvim-qt. Also undercurl not works(font is fira code NF)
Nvy
![Снимок экрана 2022-07-15 155100](https://user-images.githubusercontent.com/98752769/179209828-6372ccd5-b23e-4be0-9fd6-6434cd0d3f5a.png)
Nvim-QT
![Снимок экрана 2022-07-15 155221](https://user-images.githubusercontent.com/98752769/179209868-5311c38d-f6f3-42c9-92c0-5c4a5791c93e.png)

**Comment by RMichelsen** [comment]
The underline thickness is currently simply decided by DirectWrite.

As far as undercurl goes it currently just uses underline. As the effect is drawn "manually" with `drawRectangle` drawing a curly line is a bit cumbersome but of course possible to implement if this is something desirable.

**Comment by RMichelsen** [comment]
I will close this issue for now, if there is more interest in pursuing this please reopen and I'll reconsider, maybe with a proposal for a solution as well.
