### ISSUE TITLE
Add to `scoop`'s bucket

### ISSUE THREAD

**Issue by EtiamNullam** [RMichelsen/Nvy#59]
I think it might be worth working towards including `Nvy` in [`scoop`](https://scoop.sh)'s ([GitHub](https://github.com/ScoopInstaller/scoop)) bucket  - a popular command-line installer for `Windows`. It should fit in [`Scoop/Extras` bucket](https://github.com/ScoopInstaller/Extras).

If it was included there you can install `Nvy` via:
```
scoop bucket add extras
scoop install neovim nvy
nvy
```
...on a fresh installation to start quickly. I believe most people that use `scoop` already have [`Scoop/Extras` bucket](https://github.com/ScoopInstaller/Extras) added.

And just `scoop update nvy` to get to latest version.

Surely users would be more likely to try `Nvy` if there was an easy way to do so, especially in repository of a commonly used installer. It might also expose `Nvy` to a broader audience.

Adding it should be pretty straightforward. I might try to do it in future, when I have some more time but anyone can try. See: [ScoopInstaller/.github/CONTRIBUTING.md#for-scoop-buckets](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md#for-scoop-buckets).

**Comment by RMichelsen** [comment]
It seems we do not yet fit the criteria for inclusion in the extras bucket sadly:
- a reasonably well-known and widely used developer tool (e.g. if it's a GitHub project, it should have at least 500 stars and 150 forks)

Otherwise good idea, I've used scoop in the past myself

**Comment by EtiamNullam** [comment]
>     * a reasonably well-known and widely used developer tool (e.g. if it's a GitHub project, it should have at least 500 stars and 150 forks)

I think that's the requirement for the [`Scoop/Main` bucket](https://github.com/ScoopInstaller/Main). I was confused about that at first too.

[`Scoop/Extras`](https://github.com/ScoopInstaller/Extras):
> Scoop Extras
>
> Extra manifests for [Scoop](https://scoop.sh/), the Windows command-line installer. For manifests that **don't** fit the [Main criteria](https://github.com/ScoopInstaller/Scoop/wiki/Criteria-for-including-apps-in-the-main-bucket).

**Comment by RMichelsen** [comment]
Huh okay, in that case I'll see if I can find some time soon to open a PR. Good suggestion 👍

**Comment by RMichelsen** [comment]
I've opened an issue in the [Scoop/Extras](https://github.com/ScoopInstaller/Extras) repo: https://github.com/ScoopInstaller/Extras/issues/9277

**Comment by tan-wei** [comment]
Great if merged.
