### ISSUE TITLE
Ctrl+MouseWheel resets window font

### ISSUE THREAD

**Issue by cpkio** [RMichelsen/Nvy#6]
As seen in the following gif, window font changes upon CTRL+MouseWheel font size change.

![2020-09-28_17-10-31](https://user-images.githubusercontent.com/1917113/94443278-a4c0c980-01ad-11eb-8ade-cda13a2acca8.gif)

**Comment by RMichelsen** [comment]
This should be fixed now, I broke it accidentally. Sorry! :)
