### ISSUE TITLE
Mouse selections

### ISSUE THREAD

**Issue by cpkio** [RMichelsen/Nvy#7]
I think many would appreciate text selections by mouse. Now it is only exiting to normal mode.

**Comment by RMichelsen** [comment]
I'm not sure about this one, from what I can tell selecting text with the mouse puts you in visual mode as it does in `neovim-qt` and `neovide` for example, you would want it to stay in insert mode?

**Comment by cpkio** [comment]
For me mouse click+screen drag makes no text selection, just a text cursor running along the mouse cursor. To select I have to left-click and hold, then press V and drag.

I think any click+drag should bring you into Visual mode and select text in various modes depending on the modifier. I see Shift+Click selects the word. CTRL+Click says no tags file, which is OK.

**Comment by RMichelsen** [comment]
This seems like a bug then, I can click and drag to make a selection. Not sure how to reproduce this.

**Comment by cpkio** [comment]
My bad. My config file had no `mouse` option set, which defaulted to no mouse at all in Neovim and described behaviour in Nvy.
