### ISSUE TITLE
cmp autocomplete menu misalignment

### ISSUE THREAD

**Issue by mdealencar** [RMichelsen/Nvy#77]
When the autocomplete menu from cmp is open, the selected line has a misalignment that can be one or two char wide. This misalignment propagates to the documentation popup next to the menu (as seen in the screenshot).

![image](https://user-images.githubusercontent.com/856825/230187240-714d7fa9-dbaa-42e2-8981-9e2a1865e88a.png)

nvim-qt does not display the misalignment for the same configuration.

**Comment by Zorbn** [comment]
Do you have the bold version of your font installed? In my testing cmp uses a bold font weight for the selected line, so if you have one installed for your font the issue doesn't appear. If you only have the regular version installed then DirectWrite seems to generate a fake bold version which causes this issue.

**Comment by mdealencar** [comment]
It was a problem with the font indeed. Thanks!
