### ISSUE TITLE
CMake configuration regex error

### ISSUE THREAD

**Issue by ghost** [RMichelsen/Nvy#84]
PS C:\Users\user\Desktop\nvy> cd build
PS C:\Users\user\Desktop\nvy\build> cmake .. -GNinja
-- The C compiler identification is MSVC 19.36.32530.0
-- The CXX compiler identification is MSVC 19.36.32530.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Preview/VC/Tools/MSVC/14.36.32530/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Preview/VC/Tools/MSVC/14.36.32530/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.40.0.windows.1")
CMake Error at CMakeLists.txt:104 (string):
  string sub-command REGEX, mode REPLACE: replace expression "\1;\2;\3;\4;\5"
  contains an out-of-range escape for regex
  "v([0-9]+).([0-9]+).([0-9]+)-?([0-9]+)?(.*)?".

-- Configuring incomplete, errors occurred!

cmake version 3.26.3

**Comment by RMichelsen** [comment]
Should now be fixed via #82, please confirm.

**Comment by ghost** [comment]
> Should now be fixed via #82, please confirm.

now it builds correctly.
