### ISSUE TITLE
Touchpad scrolling is too sensitive for small moves

### ISSUE THREAD

**Issue by EtiamNullam** [RMichelsen/Nvy#87]
While touchpad scrolling is much more reliable now it's still hard to use for slow motions as its too sensitive - even a slow and small motion will scroll many lines.

I suggest there has to be a way to configure this sensitivity or tweak it so it's fine for most - I'm aware that user preference and hardware might vary.

The other problem is that single minimal move already scrolls 3 lines, while I think it should scroll only 1, to increase precision. Not sure if it's affected by system settings but it seems like not.

**Comment by RMichelsen** [comment]
I agree in general for touchpads scrolling should be less sensitive, however the way `Nvy` handles scrolling is it really just leaves it to neovim. There is no hardcoded 3 lines per scroll in `Nvy`, see: https://github.com/RMichelsen/Nvy/blob/master/src/nvim/nvim.cpp#L333

To adjust number of lines scrolled per "scroll event", see [neovim docs](https://neovim.io/doc/user/options.html#'mousescroll')

**Comment by EtiamNullam** [comment]
Sorry for the confusion with the 3 lines and thanks for the link, it helps a bit! I guess it's okay that you just pass scrolling to `nvim` - it surely makes `Nvy` easier to maintain. I thought it's up to `nvim` clients as others do it differently.

Seems like the real issue is lack of "acceleration" (slow motion should result in increased precision). I'm not a fan of it for mouse movement but I think it makes sense for this touchpad scrolling gesture.

I did a little test and scrolling slowly with touchpad gesture from top to bottom of my touchpad scroll `Nvy` for about 500-1000 lines, while a quick gesture (also along the whole surface) will scroll 100-200 (staying in contact with touchpad along the way) - as you can see it's opposite of how it should be. On `nvim-qt` its still not ideal: ~30 lines for a slow gesture and ~60 for quick one, but more acceptable and precision can be improved by slow motions. I was testing with `set mousescroll=ver:3`.

I understand that it might be tricky if it's not how `Nvy` is designed, but maybe some scroll events must be skipped when they come in slowly, but more of them has to get through the smaller the delay between the events.

**Comment by RMichelsen** [comment]
Ah yes, well at the moment we ignore the scroll wheel delta on mouse wheel event so the number of events are limited by the event loop update time and do not take into account how fast you scroll/how much you move your finger on the touchpad.

I understand this is not ideal. I will try to find time to think about a solution for this, perhaps we need send a number of scroll events based on the scroll wheel delta. 

Thank you for elaborating 🙂

**Comment by Zorbn** [comment]
@EtiamNullam Touchpad scrolling should work as expected with #98. Please give it a try if you're interested.

**Comment by EtiamNullam** [comment]
@Zorbn I'd be glad to check it out, but seems like I cannot build the project. I guess I will wait for a release.

**Comment by RMichelsen** [comment]
Closed via #98
