### ISSUE TITLE
<C-6> does not work as <C-^> to alternate between files

### ISSUE THREAD

**Issue by tamlok** [RMichelsen/Nvy#89]
This works for both Windows Terminal and neovim-qt.

In Nvy, even I add the mapping manually, it does not work.

![image](https://github.com/RMichelsen/Nvy/assets/5763157/e331f75b-0d96-44eb-b5b2-db7b789a0dce)

**Comment by Zorbn** [comment]
C-6 should work as expected by default with #91.

**Comment by tamlok** [comment]
Hi @Zorbn, when is this PR expected to be merged? Thanks!

**Comment by RMichelsen** [comment]
I will look into merging the PRs later today or tomorrow, sorry for the delay.
