### ISSUE TITLE
Screen redraw required after command

### ISSUE THREAD

**Issue by cpkio** [RMichelsen/Nvy#9]
A screen redraw required after command output.

![2020-10-08_12-55-13](https://user-images.githubusercontent.com/1917113/95443679-8acd7680-0965-11eb-8561-1911098f0bc2.gif)

**Comment by RMichelsen** [comment]
I will look into this, is there an easy way I can reproduce this?

**Comment by cpkio** [comment]
Load some file with short lines, not going to the right border. Use `:hi` command. The long lines from output of this command will "overwrite" the free screen space.

**Comment by RMichelsen** [comment]
I can't seem to reproduce with my own config, nor an empty config:
![lags](https://user-images.githubusercontent.com/42123601/95879273-75e25000-0d76-11eb-954f-c1ec7348b14e.gif)
If your config is portable (and you are willing to share it) could you post it? I'll try to reproduce with yours then.

**Comment by cpkio** [comment]
I've narrowed it down to the basic part with same problem https://pastebin.com/be4WChJ3

**Comment by RMichelsen** [comment]
Thanks, I can reproduce it with this config, I'll look into it

**Comment by RMichelsen** [comment]
Please see if the [new release](https://github.com/RMichelsen/Nvy/releases/tag/v0.1.5) fixes things for you, it should also fix the cursor `set noshowmode` issue #8

**Comment by cpkio** [comment]
Yes, this new release fixes both of the issues. Thank you!
