### ISSUE TITLE
<c-s-?> mappings don't work

### ISSUE THREAD

**Issue by mg979** [RMichelsen/Nvy#93]
As per subject, `ctrl + shift + other key` mappings don't work . Great GUI by the way.

Also `<c-.>` isn't working, and probably other keys as well.

**Comment by mg979** [comment]
I'm trying to build Nvy within the Visual Studio Developer command prompt, but I get:
```
e:\builds\Nvy\build>ninja
[2/7] Building CXX object CMakeFiles/Nvy.dir/cmake_pch.hxx.gch
FAILED: CMakeFiles/Nvy.dir/cmake_pch.hxx.gch
D:\Scoop\apps\gcc\current\bin\g++.exe -DMPACK_EXTENSIONS -DUNICODE -IE:/builds/Nvy/src -fno-rtti -fno-exceptions -std=gnu++20 -Winvalid-pch -x c++-header -include E:/builds/Nvy/build/CMakeFiles/Nvy.dir/cmake_pch.hxx -MD -MT CMakeFiles/Nvy.dir/cmake_pch.hxx.gch -MF CMakeFiles\Nvy.dir\cmake_pch.hxx.gch.d -o CMakeFiles/Nvy.dir/cmake_pch.hxx.gch -c E:/builds/Nvy/build/CMakeFiles/Nvy.dir/cmake_pch.hxx.cxx
In file included from <command-line>:
E:/builds/Nvy/build/CMakeFiles/Nvy.dir/cmake_pch.hxx:11:10: fatal error: d2d1_3.h: No such file or directory
   11 | #include <d2d1_3.h>
      |          ^~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
```

I installed Windows SDK through the Visual Studio Installer and the header is present in

     C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um\d2d1_3.h

Is there something else I need to do, or what am I doing wrong? Thank you.

**Comment by Zorbn** [comment]
Looks like Ninja is trying to compile with g++. You probably want to use Visual Studio's MSVC instead, I figure it's more likely to find that header. I'm not sure how to change the C++ compiler that Ninja uses, personally, I just use the cmake generator corresponding to whatever Visual Studio version I have and skip Ninja entirely.

**Comment by Zorbn** [comment]
This should be fixed with #95. If you get the chance and you're able to get everything to compile correctly, please give it a try.

**Comment by mg979** [comment]
Thanks, I don't have the possibility to try it right now but I will do in a few days.

**Comment by mg979** [comment]
I tried with

    cmake ..

Instead of

    cmake .. -GNinja

Then building with `msbuild`. It compiled, but I get this error when running the executable:

![image](https://github.com/RMichelsen/Nvy/assets/26169924/9437ccc0-3676-4d4f-aae0-794f6b651942)

The generated executable is also much bigger (447KB).

Anyway I tried last release (0.3.7) and it works perfectly so I'm closing this, thanks.
