### ISSUE TITLE
Can not enable strikethrough render

### ISSUE THREAD

**Issue by cagechi** [RMichelsen/Nvy#94]
Nvy: v0.3.6
Neovim: 0.9.1
OS: Windows10

Can not enable strikethrough render
for example, strikethrough syntax isn't render on nvim-orgmode.
  ` +abc+ `

**Comment by Zorbn** [comment]
This should be fixed by #96. Previously strikethrough wasn't supported. I've tested the new strikethrough formatting by creating a highlight group using the standard Vim method. If you want, you can compile my PR and test with nvim-orgmode again to make sure it works.

**Comment by cagechi** [comment]
Thanks for the update.
It's working as expected!

**Comment by RMichelsen** [comment]
Closed via #96
